### ISSUE TITLE
any R-using example with fastextR?

### ISSUE THREAD

**Issue by amjiuzi** [mlampros/fastTextR#1]
@mlampros  
thx for yr great job to bring fasttext into R
some R users like me, not so familar with python,
so can us show us some example to use fasttextR ?

**Comment by mlampros** [comment]
hello @amjiuzi,

I created a wrapper for fasttext in R ( only for the _skipgram_ and _cbow_ functions ) a while back, because I wanted to experiment with word embeddings in conjuction with my [textTinyR](https://github.com/mlampros/textTinyR) package (I wrote also a [blog post ](http://mlampros.github.io/2017/01/05/textTinyR_package/) where I also utilize the fastTextR wrapper).

I'm aware of two more wrappers for fasttext in R, which are more complete, actively maintained and can be installed from CRAN,

[fastrtext](https://cran.r-project.org/web/packages/fastrtext/fastrtext.pdf) and 
[fastTextR](https://cran.r-project.org/web/packages/fastTextR/fastTextR.pdf)

**Comment by amjiuzi** [comment]
3ku

**Comment by mlampros** [comment]
hi @amjiuzi.

I uploaded the [updated version of the fastText package](https://github.com/mlampros/fastText). It can be installed only from Github as it wasn't finally accepted from CRAN due to the fact that there are already two other versions of the same algorithm.
There is also a [blog post](http://mlampros.github.io/2019/04/11/fastText_updated_version/) explaining the new functionality.
This repository will be archived. New issues can be opened only in the new repository. Thanks.
